### ISSUE TITLE
No semi-colon ending on final statement of bridge.min.js

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Builder#14]
The minification process for bridge.min.js is changing the format of `if|else` block statements. Causes final closing statement of **bridge.min.js** to not have a closing semi-colon (`;`);

http://forums.bridge.net/forum/bridge-net-pro/bugs/406-please-terminate-bridge-min-js-with-a-semicolon-new-line

**Comment by DaniilVeriga** [comment]
Related commit - [3377b33](https://github.com/bridgedotnet/Bridge/commit/3377b33051a8b4ed746319210fd02951c25c8ab9).
