### ISSUE TITLE
outputBy=Project appends additional '.js' extension to default output file

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Builder#3]
Build.dll and Builder.exe are appending additional '.js' extension to project name, so generated files end up being `Project.js.js` and `Project.js.min.js`.

**Comment by geoffreymcgill** [comment]
Please test all `outputBy` options before closing.

**Comment by fabriciomurta** [comment]
Tests resulted in three new issues, not side effect of this but or solution:
- bridgedotnet/Bridge#100
- bridgedotnet/Bridge#101
- bridgedotnet/Bridge#102
