### ISSUE TITLE
Migrate to Automatic Package Restore

### ISSUE THREAD

**Issue by kenshinthebattosai** [bridgedotnet/Builder#5]
https://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore

**Comment by DaniilVeriga** [comment]
I agree, as soon as NuGet officially recommends that appoach rather than others in [this article](https://docs.nuget.org/consume/package-restore), we should migrate and we will. But out of curiosity, could you, please, share what exactly scenario you ran into before suggesting us the migration?
