### ISSUE TITLE
Bridge.Translator does not get 'msbuild.exe' path in a portable way.

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Builder#6]
`Bridge.Translator.Translator.GetBuilderPath()` only works for Win32NT platform. There are (hopefully portable) ways to get the path using something like `Microsoft.Build.Engine`, `Microsoft.Build.Utilities`, so the correct path for the project's `msbuild.exe` path is retrieved regardless of the OS/platform. I.e. using both MS .NET or community Mono.

The stackoverflow question [How to call MSBuild from C#](http://stackoverflow.com/questions/536539/how-to-call-msbuild-from-c-sharp) has some directions but seems it is deprecated for current .NET framework.

This one has still to be investigated, but looks like just gives a way to build without calling the executable: [How do i build a solution programatically in C#?](http://stackoverflow.com/questions/6511380/how-do-i-build-a-solution-programatically-in-c)

The bottom end of the research so far is that there's a way to do this, and such way will work on Linux and OS X builds as well.

**Comment by fabriciomurta** [comment]
The below happens when trying to build with UsingTask and MonoDevelop (XamarinStudio) -- the default build mode with freshly installed Bridge.Net NuGet packages (at least as of v1.5.0).
![screen shot 2015-06-12 at 21 05 58](https://cloud.githubusercontent.com/assets/10730372/8142035/ed41f07e-1146-11e5-9631-26596cb61ac1.png)

**Comment by fabriciomurta** [comment]
Update: Since Visual Studio 2013, `msbuild.exe` is no longer part of the .NET Framework, but has been merged to Visual Studio under `c:\Program Files\MSBuild`.

Current Bridge code refers to the (being deprecated, or no longer developed) `msbuild.exe` that's inside .NET Framework directories. This should be changed to the new MSBuild location.

In the case Bridge needs to support Visual Studio 2012 or earlier versions, there should be version tests. If VS < 12 then use Frameworks' version; else use VS's version.

**Comment by wind39** [comment]
@fabriciomurta Mono's equivalent for `msbuild` is called `xbuild`, as I mentioned in [bridgedotnet/Demos#18](https://github.com/bridgedotnet/Demos/pull/18).

**Comment by fabriciomurta** [comment]
Yes, thanks for confirming it. I've been trying to make it call `xbuild` but I got into other issues, I am hoping to be able to bring good news about that very soon.

**Comment by fabriciomurta** [comment]
I believe the fixes above fully enable unix platform support for `Bridge.Build.dll` (`Bridge.Builder.dll` from NuGet).
So far, tested using:
```
XBuild Engine Version 12.0
Mono, Version 4.0.1.0
Xamarin Studio 5.9.3 (build 1)
OS X 10.10.3 (Darwin 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```
